apiVersion: v1
kind: Service
metadata:
  name: repo-service
  namespace: sparrow-vps
spec:
  type: NodePort
  selector:
    app: repo-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
