apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-data-pvc
  namespace: sparrow-vps
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
