apiVersion: v1
kind: PersistentVolume
metadata:
  name: sparrow-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/repo-data
