apiVersion: v1
kind: PersistentVolume
metadata:
  name: sparrow-pv
  namespace: sparrow-vps
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: manual
  hostPath:
    path: /mnt/repo-data
