apiVersion: v1
kind: Service
metadata:
  name: oauth-service-svc
  namespace: sparrow-vps
spec:
  selector:
    app: oauth-service
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003
    nodePort: 30083
  type: NodePort
