apiVersion: v1
kind: Service
metadata:
  name: container-service-svc
  namespace: sparrow-vps
spec:
  selector:
    app: container-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
    nodePort: 30081
  type: NodePort
