apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-service-deployment
  namespace: sparrow-vps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-service
  template:
    metadata:
      labels:
        app: container-service
    spec:
      volumes:
      - name: repo-data-volume
        persistentVolumeClaim:
          claimName: repo-data-pvc
      containers:
      - name: container-service
        image: r3dacted42/sparrow-container-service
        volumeMounts:
        - name: repo-data-volume
          mountPath: /app/data
        ports:
        - containerPort: 8001
        env:
        - name: BASE_CLONE_PATH
          value: /app/data
        - name: ALLOWED_ORIGINS
          value: http://localhost:5173
