apiVersion: v1
kind: Service
metadata:
  name: container-service
  namespace: sparrow-vps
spec:
  type: NodePort
  selector:
    app: container-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
